# Generated by Django 3.2.9 on 2025-01-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.CharField(max_length=4)),
                ('identidadegenero', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('servico', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
