# Generated by Django 3.2.9 on 2025-02-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('identidadegenero', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=300)),
                ('servico', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
        ),
    ]
