# Generated by Django 3.2.9 on 2025-01-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
