# Generated by Django 3.2.9 on 2025-02-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendedor',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Serviço'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='identidadegenero',
            field=models.CharField(max_length=20, verbose_name='Identidade de Gênero'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='senha',
            field=models.CharField(max_length=300, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='servico',
            field=models.CharField(max_length=200, verbose_name='Serviço Oferecido'),
        ),
        migrations.AlterField(
            model_name='empreendedor',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
