# Generated by Django 3.2.9 on 2025-02-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendedores', '0002_remove_empreendedor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendedor',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
