# Generated by Django 3.2.9 on 2025-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendedores', '0004_alter_empreendedor_identidadegenero'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendedor',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='empreendedor',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
    ]
